### ISSUE TITLE
Umístění cable hole na top části

### ISSUE THREAD

**Issue by vsillik** [3DprintFIT/B212HW-Assignment#1]
Podle čeho se umisťuje cable hole u horní části? Čtu z toho plánku, že střed je uprostřed mezi switch_screw_spacing a výška od horního okraje je switch_screw_distance_from_top, nebo to zrovna tady u téhle konfigurace takhle vychází, ale řidí se to něčím jiným?

**Comment by hroncok** [comment]
V zadání je tohle:

![_](https://user-images.githubusercontent.com/2401856/158015065-59f9acc0-84e6-4f29-accb-aa8f9db2b433.png)

Ta svislá čerchovaná osa se snaží ukázat, přesně, co píšeš: že střed je uprostřed mezi switch_screw_spacing. Výška od horního okraje je switch_screw_distance_from_top poměrně -- na té vodorovné čáře sjou středy všech tří kružnic.

Ale switch_screw_spacing je vzálenost, tedy z toho samotného údaje není jasné, kde ten střed vlastně bude. To jde ale odvodit z obrázku pod tím:

![_](https://user-images.githubusercontent.com/2401856/158015117-d97134ce-bee5-4f91-a376-948aaa319725.png)
