### ISSUE TITLE
Ne můžu najít rozdíl mezi odrazkami student a reference

### ISSUE THREAD

**Issue by Rusannik** [3DprintFIT/B212HW-Assignment#4]
Dobrý den, 
Chci zeptat jestli můžete s tím nějak pomoc. Mám 16 testu z simularity score 1.0, ale test 01 a 20 má simularity 0.9999916743318814 proto vůbec ne můžu uvidět rozdíl mezi obrázkami. Používám Photoshop aby něco najít ale popixelne je to stejné. Můžete něco doporučit?
![rally_switch 01](https://user-images.githubusercontent.com/102518970/168086874-2fd8f6f1-2e50-4f96-af90-89328d272246.png)
![rally switch mine 01](https://user-images.githubusercontent.com/102518970/168086878-71efd2c5-c038-44ed-b3cf-549adfca6ff2.png)
![rally_switch reference 01](https://user-images.githubusercontent.com/102518970/168086881-4d889362-43e3-485e-ae67-d34ed24b02f2.png)

**Comment by hroncok** [comment]
Není třeba mít similarity 1. Je to jen infomarce pro mě, že obrázek nemusím kontrolovat očima.
